export const data = [
  {
    id: '0',
    name: 'Trái Đất',
    image: require('../assets/Earth.png'),
    imageBig: require('../assets/Earth-big.png'),
    style: 'earthStyle',
    moons: '1',
    age: '4.5',
    temperature: '15',
    description:
      'Hành tinh quê hương của chúng ta là hành tinh thứ ba tính từ Mặt trời và là nơi duy nhất chúng ta biết cho đến nay có các sinh vật sống. Trong khi Trái đất chỉ là hành tinh lớn thứ năm trong hệ mặt trời, nó là thế giới duy nhất trong hệ mặt trời của chúng ta có nước lỏng trên bề mặt. Chỉ lớn hơn một chút so với sao Kim gần đó, Trái đất là hành tinh lớn nhất trong số bốn hành tinh gần Mặt trời nhất, tất cả đều được làm từ đá và kim loại. Tên Trái đất ít nhất 1.000 năm tuổi. Tất cả các hành tinh, ngoại trừ Trái đất, được đặt theo tên của các vị thần và nữ thần Hy Lạp và La Mã. Tuy nhiên, cái tên Earth là một từ tiếng Đức, có nghĩa đơn giản là “mặt đất”.',
    link: 'https://solarsystem.nasa.gov/planets/earth/overview/',
  },
  {
    id: '1',
    name: 'Sao Hỏa',
    image: require('../assets/Mars.png'),
    imageBig: require('../assets/Mars-big.png'),
    style: 'marsStyle',
    moons: '2',
    age: '4.6',
    temperature: '22',
    description:
      '​Sao Hỏa là hành tinh thứ tư tính từ Mặt trời – một thế giới sa mạc lạnh lẽo, bụi bặm với bầu khí quyển rất mỏng. Sao Hỏa cũng là một hành tinh năng động với các mùa, chỏm băng ở hai cực, hẻm núi, núi lửa đã tắt và bằng chứng cho thấy nó thậm chí còn hoạt động mạnh hơn trong quá khứ. Sao Hỏa là một trong những thiên thể được khám phá nhiều nhất trong hệ mặt trời của chúng ta và đó là hành tinh duy nhất mà chúng ta đã gửi xe tự hành để đi lang thang trong cảnh quan của người ngoài hành tinh.',
    link: 'https://solarsystem.nasa.gov/planets/mars/overview/',
  },
  {
    id: '2',
    name: 'Sao Thủy',
    image: require('../assets/Mercury.png'),
    imageBig: require('../assets/Mercury-big.png'),
    style: 'mercuryStyle',
    moons: '0',
    age: '4.5',
    temperature: '400',
    description:
      'Hành tinh nhỏ nhất trong hệ mặt trời của chúng ta và gần Mặt trời nhất, Sao Thủy chỉ lớn hơn Mặt trăng của Trái đất một chút. Từ bề mặt của Sao Thủy, Mặt trời sẽ lớn hơn gấp ba lần so với khi nhìn từ Trái đất và ánh sáng mặt trời sẽ sáng hơn gấp bảy lần. Mặc dù ở gần Mặt trời, Sao Thủy không phải là hành tinh nóng nhất trong hệ Mặt trời của chúng ta – danh hiệu đó thuộc về Sao Kim gần đó, nhờ bầu khí quyển dày đặc của nó. Do quỹ đạo hình elip - hình quả trứng - của Sao Thủy và sự quay chậm chạp, Mặt trời dường như mọc lên trong một thời gian ngắn, lặn và mọc lại từ một số phần trên bề mặt hành tinh. Điều tương tự xảy ra ngược lại vào lúc hoàng hôn.',
    link: 'https://solarsystem.nasa.gov/planets/mercury/overview/',
  },
  {
    id: '3',
    name: 'Sao Thổ',
    image: require('../assets/Saturn.png'),
    imageBig: require('../assets/Saturn-big.png'),
    style: 'saturnStyle',
    moons: '53',
    age: '4.5',
    temperature: '-138',
    description:
      'Sao Thổ là hành tinh thứ sáu tính từ Mặt trời và là hành tinh lớn thứ hai trong hệ mặt trời của chúng ta. Được tô điểm bởi hàng ngàn vòng tròn xinh đẹp, Sao Thổ là duy nhất trong số các hành tinh. Nó không phải là hành tinh duy nhất có các vành đai - được tạo thành từ các khối băng và đá - nhưng không có vành đai nào ngoạn mục hoặc phức tạp như của Sao Thổ. Giống như người bạn khí khổng lồ Sao Mộc, Sao Thổ là một quả cầu khổng lồ được làm chủ yếu từ hydro và heli.',
    link: 'https://solarsystem.nasa.gov/planets/saturn/overview/',
  },
  {
    id: '4',
    name: 'Sao Mộc ',
    image: require('../assets/Jupyter.png'),
    imageBig: require('../assets/Jupyter-big.png'),
    style: 'jupyterStyle',
    moons: 'more than 75',
    age: '4.6',
    temperature: '-150',
    description:
      'Sao Mộc có một lịch sử lâu dài khiến các nhà khoa học ngạc nhiên - từ năm 1610 khi Galileo Galilei tìm thấy các mặt trăng đầu tiên bên ngoài Trái đất. Khám phá đó đã thay đổi cách chúng ta nhìn vũ trụ. Xếp thứ năm tính từ Mặt trời, cho đến nay, Sao Mộc là hành tinh lớn nhất trong hệ mặt trời – lớn hơn gấp đôi tổng khối lượng của tất cả các hành tinh khác cộng lại. Các đường sọc và vòng xoáy quen thuộc của sao Mộc thực ra là những đám mây gió lạnh chứa amoniac và nước, trôi nổi trong bầu khí quyển hydro và heli. Great Red Spot mang tính biểu tượng của sao Mộc là một cơn bão khổng lồ lớn hơn Trái đất đã hoành hành hàng trăm năm.',
    link: 'https://solarsystem.nasa.gov/planets/jupiter/overview/',
  },
  {
    id: '5',
    name: 'Sao Kim',
    image: require('../assets/Venus.png'),
    imageBig: require('../assets/Venus-big.png'),
    style: 'venusStyle',
    moons: '0',
    age: '4.5',
    temperature: '462',
    description:
      'Sao Kim là láng giềng gần nhất của Trái đất và thường được gọi là song sinh của Trái đất do kích thước và mật độ của nó. Tuy nhiên, sao Kim có bầu khí quyển độc hại, những đám mây axit sunfuric dày màu vàng và nhiệt độ khắc nghiệt khoảng 900 độ F. Bề mặt của nó chứa đầy những ngọn núi và hàng nghìn ngọn núi lửa lớn, một số trong đó có thể vẫn đang hoạt động. Áp suất không khí trên bề mặt sao Kim cao hơn 90 lần so với Trái đất, tương tự như áp suất ở độ sâu một dặm dưới đại dương. Sao Kim cũng quay ngược trục của nó, khiến mặt trời mọc ở hướng Tây và lặn ở hướng Đông.',
    link: 'https://solarsystem.nasa.gov/planets/venus/overview/',
  },
  {
    id: '6',
    name: 'Sao Thiên Vương',
    image: require('../assets/Uranus.png'),
    imageBig: require('../assets/Uranus-big.png'),
    style: 'uranusStyle',
    moons: '27',
    age: '4.6',
    temperature: '-214',
    description:
      'Sao Thiên Vương là hành tinh thứ bảy tính từ Mặt trời và có đường kính lớn thứ ba trong hệ mặt trời. Nó được William Herschel phát hiện vào năm 1781 và ban đầu được cho là một sao chổi hoặc một ngôi sao. Sau đó nó được công nhận là một hành tinh, với cái tên Uranus do nhà thiên văn học Johann Elert Bode đề xuất. Đề xuất ban đầu của Herschel, Georgium Sidus, không được cộng đồng khoa học chấp nhận. Sao Thiên Vương được đặt tên theo vị thần bầu trời của Hy Lạp.',
    link: 'https://solarsystem.nasa.gov/planets/uranus/overview/',
  },
  {
    id: '7',
    name: 'Sao Hải Vương',
    image: require('../assets/Neptune.png'),
    imageBig: require('../assets/Neptune-big.png'),
    style: 'neptuneStyle',
    moons: '14',
    age: '4.5',
    temperature: '-214',
    description:
      'Tối tăm, lạnh giá và bị thổi bay bởi những cơn gió siêu thanh, băng khổng lồ Neptune là hành tinh thứ tám và xa nhất trong hệ mặt trời của chúng ta. Cách xa Mặt trời hơn 30 lần so với Trái đất, Sao Hải Vương là hành tinh duy nhất trong hệ mặt trời của chúng ta không thể nhìn thấy bằng mắt thường và là hành tinh đầu tiên được toán học dự đoán trước khi phát hiện ra nó. Năm 2011, Sao Hải Vương hoàn thành quỹ đạo 165 năm đầu tiên kể từ khi được phát hiện vào năm 1846.',
    link: 'https://solarsystem.nasa.gov/planets/neptune/overview/',
  },
];
